// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        asd: string;
        atrule: string;
        "attr-name": string;
        "attr-value": string;
        block: string;
        bold: string;
        boolean: string;
        builtin: string;
        cdata: string;
        char: string;
        "class-name": string;
        comment: string;
        constant: string;
        deleted: string;
        doctype: string;
        entity: string;
        function: string;
        important: string;
        inserted: string;
        italic: string;
        keyword: string;
        "language-css": string;
        namespace: string;
        number: string;
        operator: string;
        pre: string;
        prolog: string;
        property: string;
        punctuation: string;
        regex: string;
        selector: string;
        string: string;
        style: string;
        symbol: string;
        tag: string;
        token: string;
        url: string;
        variable: string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
