// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
  export interface IStyleCss {
    annotation: string;
    codeblock: string;
    home: string;
    leftside: string;
    preview: string;
    resizer: string;
    rightside: string;
    rightside2: string;
    'text-area': string;
    textvalue: string;
  }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
